# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'scryptExample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
#  use_frameworks!
  use_modular_headers!
  pod 'CryptoSwift', '~> 0.11'
  pod 'scrypt', '~> 1.3'
  # Pods for scryptExample

  target 'scryptExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'scryptExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
